# Generated by Django 5.1.7 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employeetask_leaverequest_worksubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='type',
            field=models.CharField(blank=True, default='Document', max_length=60),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
